### Change this to use a different container image for cloudflared
image:
  repository: cloudflare/cloudflared
  tag: 2022.2.2

### How many replicas to run
replicaCount: 3

### Argo Tunnel ID
tunnelID: ""

### All of these values can be found in the auth json file generated on tunnel creation.
auth:
  accountTag: ""
  tunnelName: ""
  tunnelSecret: ""

### Whether argo tunnel will route WARP traffic to local subnets
warpRouting: false

### Set up custom ingress rules here
ingress:
  - service: http_status:404
