apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-deployment
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: {{ .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - args:
        - tunnel
        - --no-autoupdate
        - --config
        - /etc/cloudflared/config.yaml
        - run
        name: cloudflared-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/cloudflared/{{ required "A valid .Values.tunnelID entry required!" .Values.tunnelID }}.json
          name: tunnel-secret-vol
          subPath: {{ required "A valid .Values.tunnelID entry required!" .Values.tunnelID }}.json
        - mountPath: /etc/cloudflared/config.yaml
          name: cloudflared-config-vol
          subPath: config.yaml
      imagePullSecrets:
      - name: tunnel-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tunnel-secret-vol
        secret:
          defaultMode: 420
          optional: false
          secretName: tunnel-secret
      - configMap:
          defaultMode: 420
          name: cloudflared-config
          optional: false
        name: cloudflared-config-vol
