apiVersion: v1
kind: Secret
metadata:
  name: tunnel-secret
type: Opaque
stringData:
  {{ required "A valid .Values.tunnelID entry required!" .Values.tunnelID }}.json: >
    {
      "AccountTag": "{{ required "A valid .Values.auth.accountTag entry required!" .Values.auth.accountTag }}",
      "TunnelSecret": "{{ required "A valid .Values.auth.tunnelSecret entry required!" .Values.auth.tunnelSecret }}",
      "TunnelID": "{{ required "A valid .Values.tunnelID entry required!" .Values.tunnelID }}",
      "TunnelName": "{{ required "A valid .Values.auth.tunnelName entry required!" .Values.auth.tunnelName }}"
    }
